commit 2018-07-04

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -15319,6 +15319,80 @@ if test "${enable_testlib+set}" = set; then
   enableval=$enable_testlib;
 fi
 
+
+
+pkg_failed=no
+{ $as_echo "$as_me:$LINENO: checking for CHECK" >&5
+$as_echo_n "checking for CHECK... " >&6; }
+
+if test -n "$CHECK_CFLAGS"; then
+    pkg_cv_CHECK_CFLAGS="$CHECK_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"check >= 0.9.4\"") >&5
+  ($PKG_CONFIG --exists --print-errors "check >= 0.9.4") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_CHECK_CFLAGS=`$PKG_CONFIG --cflags "check >= 0.9.4" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$CHECK_LIBS"; then
+    pkg_cv_CHECK_LIBS="$CHECK_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"check >= 0.9.4\"") >&5
+  ($PKG_CONFIG --exists --print-errors "check >= 0.9.4") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_CHECK_LIBS=`$PKG_CONFIG --libs "check >= 0.9.4" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        CHECK_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "check >= 0.9.4" 2>&1`
+        else
+	        CHECK_PKG_ERRORS=`$PKG_CONFIG --print-errors "check >= 0.9.4" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$CHECK_PKG_ERRORS" >&5
+
+	{ $as_echo "$as_me:$LINENO: result: no" >&5
+$as_echo "no" >&6; }
+
+        enable_testlib="no"
+
+elif test $pkg_failed = untried; then
+
+        enable_testlib="no"
+
+else
+	CHECK_CFLAGS=$pkg_cv_CHECK_CFLAGS
+	CHECK_LIBS=$pkg_cv_CHECK_LIBS
+        { $as_echo "$as_me:$LINENO: result: yes" >&5
+$as_echo "yes" >&6; }
+
+        enable_testlib="yes"
+
+fi
  if test "x$enable_testlib" != "xno"; then
   COND_BUILD_TEST_TRUE=
   COND_BUILD_TEST_FALSE='#'
@@ -15328,7 +15402,12 @@ else
 fi
 
 
-# AC_MSG_NOTICE(["Build: $ax_cv_c_compiler_vendor"])
+
+
+{ $as_echo "$as_me:$LINENO: \"Build tests: $enable_testlib\"" >&5
+$as_echo "$as_me: \"Build tests: $enable_testlib\"" >&6;}
+{ $as_echo "$as_me:$LINENO: \"Build vendor: $ax_cv_c_compiler_vendor\"" >&5
+$as_echo "$as_me: \"Build vendor: $ax_cv_c_compiler_vendor\"" >&6;}
 
 mkdir -p build/obj
 
